#!/bin/bash

cd `dirname $0`

echo --- python3 build
python3 build

echo --- git status
git status

echo --- git add .
git add .

echo --- git commit -m $(date +%y-%m-%d)
git commit -m $(date +%y-%m-%d)

echo --- git push
git push

echo ============
echo 
